# ============ Settings ============
# machine info
num_gpus: 1

# mode
test: True
train: False

# models
generator: "generator_cnn"
discriminator: "discriminator_patchgan"

# config
plotting: True
debug: True
logging: True

# hyperparameters
img_size: [256, 256, 1]
training_samples: 500
testing_samples: 100
max_iters: 100000
global_batch_size: 8
replica_batch_size: 8

# directories
dataset_dir: '../sketch_ds/'
log_dir: '../logs/'
checkpoint_dir: '../checkpoints/'
checkpoint_prefix: '../checkpoints/ckpt'

# checkpoints
checkpoint_nsave: 100
checkpoint_save: False
checkpoint_load: False

# loss
disc_loss: True
l1_loss: True
l1_lambda: 1.
