# ============ Settings ============
# machine info
num_gpus: 1

# hyperparameters
img_size: [128, 128, 1]
training_samples: 3000
max_iters: 100000
batch_size: 4
plotting: True
debug: True

# directories
dataset_dir: 'intel_dataset/'
log_dir: 'logs/'
checkpoint_dir: 'checkpoints/'
checkpoint_prefix: 'checkpoints/ckpt'

# checkpoints
checkpoint_nsave: 20
checkpoint_load: False

# loss
disc_loss: True
l1_loss: True
