# ============ Settings ============
# machine info
num_gpus: 1

# hyperparameters
img_size: [256, 256, 1]

# directories
dataset_dir: 'dataset/'
log_dir: 'logs/'
checkpoint_dir: 'checkpoints/'
checkpoint_prefix: 'checkpoints/ckpt'

# checkpoints
checkpoint_nsave: 50
checkpoint_load: False

# training
max_iters: 100000

# loss
disc_loss: True
l1_loss: True
