# ============ Settings ============
# machine info
num_gpus: 1

# config
plotting: True
debug: True
logging: True

# hyperparameters
img_size: [256, 256, 1]
training_samples: 100
max_iters: 100000
batch_size: 4

# directories
dataset_dir: 'dataset/'
log_dir: 'logs/'
checkpoint_dir: 'checkpoints/'
checkpoint_prefix: 'checkpoints/ckpt'

# checkpoints
checkpoint_nsave: 20
checkpoint_save: False
checkpoint_load: False

# loss
disc_loss: True
l1_loss: True
l1_lambda: 3
