# ============ Settings ============
# machine info
num_gpus: 1

# mode
test: True
train: False

# config
plotting: False
debug: False
logging: True

# hyperparameters
img_size: [256, 256, 1]
training_samples: 100
testing_samples: 100
max_iters: 100000
global_batch_size: 16
replica_batch_size: 16

# directories
dataset_dir: '../dataset/'
log_dir: '../logs/'
checkpoint_dir: '../checkpoints/'
checkpoint_prefix: '../checkpoints/ckpt'

# checkpoints
checkpoint_nsave: 1
checkpoint_save: False
checkpoint_load: True

# loss
disc_loss: True
l1_loss: True
l1_lambda: 1.
