# ============ Settings ============
# machine info
num_gpus: 1

# hyperparameters
full_img_size: [256, 256, 1]
img_size: [256, 256]
channels: [1]
training_samples: 3000
max_iters: 100000
batch_size: 4
plotting: True
debug: True

# directories
dataset_dir: 'dataset/'
log_dir: 'logs/'
checkpoint_dir: 'checkpoints/'
checkpoint_prefix: 'checkpoints/ckpt'

# checkpoints
checkpoint_nsave: 20
checkpoint_load: False

# loss
disc_loss: True
l1_loss: True
l1_lambda: 3
